# Generated by Django 5.0.6 on 2024-05-12 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=50)),
                ('zip', models.IntegerField(unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('web', models.URLField()),
                ('age', models.IntegerField()),
            ],
        ),
    ]
