# Generated by Django 5.0.6 on 2024-05-12 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='zip',
            field=models.IntegerField(),
        ),
    ]
